In [1]:
import jax
import jax.numpy as jnp

# Verifica versione
print(jax.__version__)

# Verifica dispositivo disponibile
print(jax.devices())

# Test base
x = jnp.array([1.0, 2.0, 3.0])
print(x)

0.9.2
[CpuDevice(id=0)]
[1. 2. 3.]


In [2]:
#Unico modo per "modificare" un array
x = x.at[0].set(10)
print(x)

[10.  2.  3.]


In [3]:
#Operazioni Elementari
x = jnp.array([1.,2.,3.])
y = jnp.array([4.,5.,6.])

print(x+y)
print(x*y)
print(jnp.sum(x))

[5. 7. 9.]
[ 4. 10. 18.]
6.0


In [4]:
x = jnp.array([1.,2.,3.])

print(x + 1)

[2. 3. 4.]


In [5]:
#le funzioni sono già vettorizzate
x = jnp.array([1.,2.,3.])

print(jnp.exp(x))
print(jnp.sin(x))
print(jnp.sqrt(x))

[ 2.7182817  7.389056  20.085537 ]
[0.84147096 0.9092974  0.14112   ]
[1.        1.4142135 1.7320508]


In [6]:
#egualmente se la funzione è definita da noi, è già vettorizzata
def f(x):
    return x**2 + 3*x

print(f(2.))
print(f(jnp.array([1.,2.,3.])))

10.0
[ 4. 10. 18.]


In [7]:
#Ora vediamo l'utilià di JAX nelle derivate automatiche
from jax import grad

In [8]:
def V(x):
    return x**4 - 2*x**2

In [9]:
dV = grad(V)

print(dV(1.0))

0.0


In [10]:
#con jax jit non si può usare if quindi si usa where:
def f(x):
    return jnp.where(x > 0, x**2, -x**2)
print(f(2.0))
print(f(-2.0))

# where è nella forma(condizione, valore se vero, valore se falso)

4.0
-4.0
